[package]
name = "kiro-generator"
version = "0.1.0"
edition = "2024"
description = "Kiro CLI agent config generator"
repository = "https://github.com/CarteraMesh/kiro-generator"
license = "MIT"
authors = ["gh@cartera-mesh.com"]
documentation = "https://docs.rs/kiro-generator"
homepage = "https://github.com/CarteraMesh/kiro-generator"
keywords = []
categories = []
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = { version = "0.1" }

[dev-dependencies]
anyhow = { version = "1" }
tracing-subscriber = { version = "0.3", features = ["env-filter", "serde"] }
tokio = { version = "1", features = [ "full"] }
dotenvy= "0.15"
lazy_static = "1.4.0"
