"$schema" = "https://kiro-generator.io/manifest.json"

# Kiro Generator Manifest
# Declare your agents and their relationships here
[agents]
# git is a simple template what allows and denies access to git CLI commands
# see agents/git.toml for details
git = { template = true }
default = { inherits = ["git"] }  # consume or merge the properties of git agent template
