name = "default_agent_cli"
description = "Default agent for Kiro"
tools = ["*"]
allowedTools = ["read", "knowledge", "@fetch"]

resources = ["file://README.md", "file://.amazonq/rules/**/*.md"]
includeMcpJson = false

[toolAliases]

[hooks]
userPromptSubmit = {}

[hooks.agentSpawn.echo]
command = "echo My name is Bob"
timeout_ms = 4000
cache_ttl_seconds = 300

[toolsSettings]
read = { deniedPaths = [".*Cargo.toml.*", ".*yarn.lock.*"] }
write = { deniedPaths = [".*Cargo.toml.*"] }
aws = { autoAllowReadonly = true }

[toolsSettings.shell]
allowedCommands = ["git status", "git fetch", "git diff .*", "git pull .*", "yarn .*", "pulumi preview .*", "kubectl .*", "pdf2.*", "ps .*", "timeout.*", "pgrep.*"]
deniedCommands = ["git commit .*", "git push .*", "kubectl .*delete*", ".*delete.*", "pulumi up.*", "^rm .*", ".*destroy.*", ".*rollout.*", ".*kill.*"]
autoAllowReadonly = true

[mcpServers.rustdocs]
type = "stdio"
command = "rust-docs-mcp"
args = []
timeout = 1200
disabled = false

[mcpServers.cargo]
command = "cargo-mcp"
args = []
timeout = 120000
disabled = false
