[book]
title = "Kiro Agent Generator"
authors = ["Doug Chimento"]
language = "en"
src = "src"

[build]
build-dir = "book"
create-missing = false
use-default-preprocessors = true

[output.html]
default-theme = "Rust"
preferred-dark-theme = "Ayu"
smart-punctuation = true
mathjax-support = true
#copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/dougEfresh/kiro-generator"
edit-url-template = "https://github.com/dougEfresh/kiro-generator/edit/main/docs/{path}"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

[preprocessor]
# [preprocessor.embedify]
# scroll-to-top.enable = true
# footer.enable = true
# footer.message = "Copyright © 2025 • Created with SOL by [dougEfresh](https://github.com/dougeEfresh)"

# announcement-banner.enable = false
# announcement-banner.id = "3.0.11"
# announcement-banner.message = "*New version [3.0.11](https://github.com/dougEfresh/kiro-generator/releases/tag/3.0.11)*"
