name: release-bin
permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  releaser:
    name: release-bin
    uses: carteramesh/ci/.github/workflows/rust-bin.yml@main
    secrets: inherit
    with:
      package: "kiro-generator"
      bin: "kg"
