name: release
permissions:
  contents: write
  checks: write
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version to release"
        required: true
        type: choice
        default: patch
        options:
          - patch
          - rc
          - minor
          - beta
          - alpha
          - major
          - release
jobs:
  releaser:
    name: release
    uses: dougEfresh/ci/.github/workflows/rust-release.yml@main
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      package: "kiro-generator"
