permissions:
  contents: read
  checks: write
on:
  schedule:
    - cron: "7 7 1,7,20 * *"
name: rolling
jobs:
  checker:
    name: Rust Checks
    if: false
    uses: carteramesh/ci/.github/workflows/rust.yml@main
    secrets: inherit
    with:
      runner: ${{ vars.RUNNER }}
